//* Aufgabe 1
db.emp.find({
    sal: 1500
}).pretty()
//* Aufgabe 2
db.emp.find({
    sal:{ $gt: 2500, $lt: 2900}
}).pretty()
//* Aufgabe 3
db.emp.insert({
   "ename": "John Doe",
   "sal": 3100,
   "job": "CONSULT",
   "dept": "SALES",
})
// ObjectId autogenerated if not specified
//* Aufgabe 4
db.emp.update({
    ename: "KING",
},
{
    $set: {
        sal: 5300
    }
}
)
//find him
db.emp.find({ ename: "KING"}).pretty()

//* Aufgabe 5
db.emp.aggregate([
    {
        $lookup:
        {
            from: "dept",
            localField: "dept",
            foreignField: "name",
            as: "department"
        }
    }
]).pretty()